#!/usr/bin/env python3
"""
Script to plot control data from CSV files generated by the controller.

Usage:
    python plot_ctrl.py [--data=/path/to/folder] [--start-time=5.0] [--end-time=30.0]

If no data path is provided, uses the most recent folder from ctrl_logs.
"""

import argparse
import csv
import glob
import os
import sys
from pathlib import Path
from typing import Optional, Dict, Any

import matplotlib.pyplot as plt
import numpy as np


def find_most_recent_ctrl_folder() -> Optional[str]:
    """Find the most recent control log folder in ctrl_logs directory."""
    robot_rl_root = os.environ.get("ROBOT_RL_ROOT", "")
    if not robot_rl_root:
        print("Error: ROBOT_RL_ROOT environment variable not set")
        return None

    ctrl_logs_dir = os.path.join(robot_rl_root, "ctrl_logs")
    if not os.path.exists(ctrl_logs_dir):
        print(f"Error: ctrl_logs directory not found at {ctrl_logs_dir}")
        return None

    folders = glob.glob(os.path.join(ctrl_logs_dir, "*"))
    folders = [f for f in folders if os.path.isdir(f)]

    if not folders:
        print(f"Error: No control log folders found in {ctrl_logs_dir}")
        return None

    folders.sort(key=os.path.getmtime, reverse=True)
    most_recent = folders[0]
    print(f"Using most recent folder: {most_recent}")
    return most_recent


def load_column_names(folder_path: str) -> list[str]:
    """Load column names from fields.csv."""
    fields_path = os.path.join(folder_path, "fields.csv")
    if not os.path.exists(fields_path):
        raise FileNotFoundError(f"fields.csv not found in {folder_path}")

    with open(fields_path, 'r') as f:
        header_line = f.readline().strip()
        columns = header_line.split(',')

    print(f"Loaded {len(columns)} column names from fields.csv")
    return columns


def load_ctrl_data(folder_path: str) -> Dict[str, np.ndarray]:
    """Load control data from folder into a dictionary keyed by column name."""
    csv_path = os.path.join(folder_path, "g1_control.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"g1_control.csv not found in {folder_path}")

    columns = load_column_names(folder_path)

    # Initialize lists for each column
    data = {col: [] for col in columns}

    print(f"Loading data from: {csv_path}")

    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        for row_idx, row in enumerate(reader):
            if len(row) != len(columns):
                print(f"Warning: Row {row_idx} has {len(row)} values, expected {len(columns)}")
                continue

            for col, val in zip(columns, row):
                data[col].append(float(val))

            if row_idx % 1000 == 0 and row_idx > 0:
                print(f"Loaded {row_idx} rows...")

    # Convert to numpy arrays
    for col in columns:
        data[col] = np.array(data[col])

    n_samples = len(data["time"])
    time_span = data["time"][-1] - data["time"][0] if n_samples > 0 else 0
    print(f"Loaded {n_samples} data points spanning {time_span:.2f} seconds")

    return data


def quat_to_euler(qx: np.ndarray, qy: np.ndarray, qz: np.ndarray, qw: np.ndarray):
    """Convert quaternion to roll, pitch, yaw (in radians)."""
    # Roll (x-axis rotation)
    sinr_cosp = 2 * (qw * qx + qy * qz)
    cosr_cosp = 1 - 2 * (qx * qx + qy * qy)
    roll = np.arctan2(sinr_cosp, cosr_cosp)

    # Pitch (y-axis rotation)
    sinp = 2 * (qw * qy - qz * qx)
    pitch = np.where(np.abs(sinp) >= 1, np.sign(sinp) * np.pi / 2, np.arcsin(sinp))

    # Yaw (z-axis rotation)
    siny_cosp = 2 * (qw * qz + qx * qy)
    cosy_cosp = 1 - 2 * (qy * qy + qz * qz)
    yaw = np.arctan2(siny_cosp, cosy_cosp)

    return roll, pitch, yaw


def get_joint_names_pos(data: Dict[str, np.ndarray]) -> list[str]:
    """Extract joint names for positions from the data columns."""
    joint_names = []
    for col in data.keys():
        if col.startswith("pos_"):
            joint_name = col[4:]  # Remove "pos_" prefix
            joint_names.append(joint_name)
    return joint_names


def get_joint_names_act(data: Dict[str, np.ndarray]) -> list[str]:
    """Extract joint names for actions from the data columns."""
    joint_names = []
    for col in data.keys():
        if col.startswith("act_"):
            joint_name = col[4:]  # Remove "act_" prefix
            joint_names.append(joint_name)
    return joint_names


def plot_joint_positions(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot joint positions with action targets (only for joints with actions)."""
    time = data["time"]
    # Use action joint names since we want to compare pos vs action
    joint_names = get_joint_names_act(data)

    fig, axes = plt.subplots(4, 6, figsize=(24, 16))
    fig.suptitle('Joint Positions vs Action Targets', fontsize=16)

    for idx, joint_name in enumerate(joint_names):
        row = idx // 6
        col = idx % 6
        ax = axes[row, col]

        pos_key = f"pos_{joint_name}"
        act_key = f"act_{joint_name}"

        ax.plot(time, data[pos_key], 'b-', linewidth=1, label='Position', alpha=0.7)
        ax.plot(time, data[act_key], 'r-', linewidth=1, label='Action Target', alpha=0.7)

        # Shorten joint name for title
        short_name = joint_name.replace("_joint", "")
        ax.set_title(short_name, fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Angle (rad)')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=7)

    # Hide unused subplots
    for idx in range(len(joint_names), 24):
        row = idx // 6
        col = idx % 6
        axes[row, col].set_visible(False)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'joint_positions.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_joint_velocities(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot joint velocities (all 27 joints from estimator)."""
    time = data["time"]
    joint_names = get_joint_names_pos(data)  # Use pos names (27 joints)

    fig, axes = plt.subplots(5, 6, figsize=(24, 20))
    fig.suptitle('Joint Velocities', fontsize=16)

    for idx, joint_name in enumerate(joint_names):
        row = idx // 6
        col = idx % 6
        ax = axes[row, col]

        vel_key = f"vel_{joint_name}"
        ax.plot(time, data[vel_key], 'g-', linewidth=1)

        short_name = joint_name.replace("_joint", "")
        ax.set_title(short_name, fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Velocity (rad/s)')
        ax.grid(True, alpha=0.3)

    # Hide unused subplots
    for idx in range(len(joint_names), 30):
        row = idx // 6
        col = idx % 6
        axes[row, col].set_visible(False)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'joint_velocities.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_all_joint_positions(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot all joint positions (27 joints from estimator)."""
    time = data["time"]
    joint_names = get_joint_names_pos(data)

    fig, axes = plt.subplots(5, 6, figsize=(24, 20))
    fig.suptitle('All Joint Positions (from Estimator)', fontsize=16)

    for idx, joint_name in enumerate(joint_names):
        row = idx // 6
        col = idx % 6
        ax = axes[row, col]

        pos_key = f"pos_{joint_name}"
        ax.plot(time, data[pos_key], 'b-', linewidth=1)

        short_name = joint_name.replace("_joint", "")
        ax.set_title(short_name, fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Angle (rad)')
        ax.grid(True, alpha=0.3)

    # Hide unused subplots
    for idx in range(len(joint_names), 30):
        row = idx // 6
        col = idx % 6
        axes[row, col].set_visible(False)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'all_joint_positions.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_loop_rate(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot loop rate (time difference between samples)."""
    time = data["time"]
    dt = np.diff(time)
    time_mid = time[:-1] + dt / 2  # Midpoints for dt values

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle('Loop Rate Analysis', fontsize=16)

    # Plot dt over time
    axes[0].plot(time_mid, dt * 1000, 'b-', linewidth=0.5)
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('dt (ms)')
    axes[0].set_title('Loop Period Over Time')
    axes[0].grid(True, alpha=0.3)

    # Add statistics
    mean_dt = np.mean(dt) * 1000
    std_dt = np.std(dt) * 1000
    axes[0].axhline(y=mean_dt, color='r', linestyle='--', label=f'Mean: {mean_dt:.2f} ms')
    axes[0].legend()

    # Histogram of dt
    axes[1].hist(dt * 1000, bins=50, edgecolor='black', alpha=0.7)
    axes[1].set_xlabel('dt (ms)')
    axes[1].set_ylabel('Count')
    axes[1].set_title(f'Loop Period Distribution (mean={mean_dt:.2f}ms, std={std_dt:.2f}ms)')
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'loop_rate.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_commanded_velocity(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot commanded velocities."""
    time = data["time"]

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle('Commanded Velocity', fontsize=16)

    axes[0].plot(time, data["cmd_vx"], 'b-', linewidth=1)
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Velocity (m/s)')
    axes[0].set_title('cmd_vx (Forward)')
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(time, data["cmd_vy"], 'g-', linewidth=1)
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Velocity (m/s)')
    axes[1].set_title('cmd_vy (Lateral)')
    axes[1].grid(True, alpha=0.3)

    axes[2].plot(time, data["cmd_wz"], 'r-', linewidth=1)
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('Angular Velocity (rad/s)')
    axes[2].set_title('cmd_wz (Yaw Rate)')
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'commanded_velocity.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_angular_velocity(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot angular velocity from IMU."""
    time = data["time"]

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle('Angular Velocity (IMU)', fontsize=16)

    axes[0].plot(time, data["ang_vel_x"], 'b-', linewidth=1)
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Angular Velocity (rad/s)')
    axes[0].set_title('ang_vel_x (Roll Rate)')
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(time, data["ang_vel_y"], 'g-', linewidth=1)
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Angular Velocity (rad/s)')
    axes[1].set_title('ang_vel_y (Pitch Rate)')
    axes[1].grid(True, alpha=0.3)

    axes[2].plot(time, data["ang_vel_z"], 'r-', linewidth=1)
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('Angular Velocity (rad/s)')
    axes[2].set_title('ang_vel_z (Yaw Rate)')
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'angular_velocity.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def plot_orientation(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot orientation as roll-pitch-yaw converted from quaternion."""
    time = data["time"]

    roll, pitch, yaw = quat_to_euler(
        data["quat_x"], data["quat_y"], data["quat_z"], data["quat_w"]
    )

    # Convert to degrees for easier interpretation
    roll_deg = np.rad2deg(roll)
    pitch_deg = np.rad2deg(pitch)
    yaw_deg = np.rad2deg(yaw)

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle('Orientation (Roll-Pitch-Yaw from Quaternion)', fontsize=16)

    axes[0].plot(time, roll_deg, 'b-', linewidth=1)
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Angle (deg)')
    axes[0].set_title('Roll')
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(time, pitch_deg, 'g-', linewidth=1)
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Angle (deg)')
    axes[1].set_title('Pitch')
    axes[1].grid(True, alpha=0.3)

    axes[2].plot(time, yaw_deg, 'r-', linewidth=1)
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('Angle (deg)')
    axes[2].set_title('Yaw')
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    output_path = os.path.join(save_dir, 'orientation.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


def filter_time_range(data: Dict[str, np.ndarray], start_time: float,
                      end_time: Optional[float]) -> Dict[str, np.ndarray]:
    """Filter data to a specific time range."""
    time = data["time"]

    start_idx = np.searchsorted(time, start_time)
    start_idx = max(0, min(start_idx, len(time) - 1))

    if end_time is not None:
        end_idx = np.searchsorted(time, end_time)
        end_idx = max(0, min(end_idx, len(time)))
    else:
        end_idx = len(time)

    filtered = {}
    for key, arr in data.items():
        filtered[key] = arr[start_idx:end_idx]

    print(f"Filtered to time range [{time[start_idx]:.2f}, {time[min(end_idx-1, len(time)-1)]:.2f}] s")
    return filtered


def main():
    parser = argparse.ArgumentParser(description='Plot control data from CSV files')
    parser.add_argument('--data', help='Path to control log folder (if not provided, uses most recent)')
    parser.add_argument('--start-time', type=float, default=0.0, help='Start time for plotting (seconds)')
    parser.add_argument('--end-time', type=float, default=None, help='End time for plotting (seconds)')
    args = parser.parse_args()

    # Determine folder to use
    if args.data:
        folder_path = args.data
        if not os.path.exists(folder_path):
            print(f"Error: Folder not found: {folder_path}")
            sys.exit(1)
    else:
        folder_path = find_most_recent_ctrl_folder()
        if folder_path is None:
            sys.exit(1)

    # Load data
    data = load_ctrl_data(folder_path)

    # Apply time filtering
    if args.start_time > 0.0 or args.end_time is not None:
        data = filter_time_range(data, args.start_time, args.end_time)

    # Generate all plots
    plot_joint_positions(data, folder_path)      # 21 joints with action targets
    plot_all_joint_positions(data, folder_path)  # All 27 joints
    plot_joint_velocities(data, folder_path)     # All 27 joints
    plot_loop_rate(data, folder_path)
    plot_commanded_velocity(data, folder_path)
    plot_angular_velocity(data, folder_path)
    plot_orientation(data, folder_path)

    print(f"\nAll plots saved to: {folder_path}")


if __name__ == "__main__":
    main()
