#!/usr/bin/env python3
"""
Script to plot odometry data from CSV files generated by high_level_control.py

Usage:
    python plot_odom.py [path_to_csv]
    
If no path is provided, plots the most recent CSV file from odom_logs.
"""

import argparse
import csv
import glob
import os
import sys
from pathlib import Path
from typing import Optional, Tuple, List

import matplotlib.pyplot as plt
import numpy as np


def find_most_recent_odom_csv() -> Optional[str]:
    """Find the most recent odometry CSV file in odom_logs directory."""
    # Get ROBOT_RL_ROOT from environment
    robot_rl_root = os.environ.get("ROBOT_RL_ROOT", "")
    if not robot_rl_root:
        print("Error: ROBOT_RL_ROOT environment variable not set")
        return None
    
    odom_logs_dir = os.path.join(robot_rl_root, "odom_logs")
    if not os.path.exists(odom_logs_dir):
        print(f"Error: odom_logs directory not found at {odom_logs_dir}")
        return None
    
    # Find all CSV files in timestamped subdirectories
    csv_pattern = os.path.join(odom_logs_dir, "*", "odom_data.csv")
    csv_files = glob.glob(csv_pattern)
    
    if not csv_files:
        print(f"Error: No odometry CSV files found in {odom_logs_dir}")
        return None
    
    # Sort by modification time and return most recent
    csv_files.sort(key=os.path.getmtime, reverse=True)
    most_recent = csv_files[0]
    print(f"Using most recent CSV: {most_recent}")
    return most_recent


def load_odom_data(csv_path: str) -> Tuple[np.ndarray, ...]:
    """Load odometry data from CSV file."""
    data = {
        'time': [], 'pos_x': [], 'pos_y': [], 'pos_z': [],
        'quat_x': [], 'quat_y': [], 'quat_z': [], 'quat_w': [],
        'vel_x': [], 'vel_y': [], 'vel_z': [],
        'ang_vel_x': [], 'ang_vel_y': [], 'ang_vel_z': [],
        'yaw': []
    }
    
    try:
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                for key in data.keys():
                    data[key].append(float(row[key]))
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        sys.exit(1)
    
    # Convert to numpy arrays
    return tuple(np.array(data[key]) for key in data.keys())


def plot_position_velocity(time: np.ndarray, pos_x: np.ndarray, pos_y: np.ndarray, pos_z: np.ndarray,
                          vel_x: np.ndarray, vel_y: np.ndarray, vel_z: np.ndarray,
                          save_dir: str) -> None:
    """Create and save position and velocity plots."""
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle('Position and Velocity Data', fontsize=16)
    
    # Position plots
    axes[0, 0].plot(time, pos_x, 'b-', linewidth=2)
    axes[0, 0].set_title('Position X')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('Position (m)')
    axes[0, 0].grid(True, alpha=0.3)
    
    axes[0, 1].plot(time, pos_y, 'g-', linewidth=2)
    axes[0, 1].set_title('Position Y')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Position (m)')
    axes[0, 1].grid(True, alpha=0.3)
    
    axes[0, 2].plot(time, pos_z, 'r-', linewidth=2)
    axes[0, 2].set_title('Position Z')
    axes[0, 2].set_xlabel('Time (s)')
    axes[0, 2].set_ylabel('Position (m)')
    axes[0, 2].grid(True, alpha=0.3)
    
    # Velocity plots
    axes[1, 0].plot(time, vel_x, 'b-', linewidth=2)
    axes[1, 0].set_title('Velocity X')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Velocity (m/s)')
    axes[1, 0].grid(True, alpha=0.3)
    
    axes[1, 1].plot(time, vel_y, 'g-', linewidth=2)
    axes[1, 1].set_title('Velocity Y')
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('Velocity (m/s)')
    axes[1, 1].grid(True, alpha=0.3)
    
    axes[1, 2].plot(time, vel_z, 'r-', linewidth=2)
    axes[1, 2].set_title('Velocity Z')
    axes[1, 2].set_xlabel('Time (s)')
    axes[1, 2].set_ylabel('Velocity (m/s)')
    axes[1, 2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'position_velocity.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved position/velocity plot to: {output_path}")


def plot_orientation_angular_velocity(time: np.ndarray, quat_x: np.ndarray, quat_y: np.ndarray,
                                     quat_z: np.ndarray, quat_w: np.ndarray, ang_vel_x: np.ndarray,
                                     ang_vel_y: np.ndarray, ang_vel_z: np.ndarray, yaw: np.ndarray,
                                     save_dir: str) -> None:
    """Create and save orientation and angular velocity plots."""
    fig, axes = plt.subplots(3, 3, figsize=(15, 12))
    fig.suptitle('Orientation and Angular Velocity Data', fontsize=16)
    
    # Quaternion plots
    axes[0, 0].plot(time, quat_x, 'b-', linewidth=2)
    axes[0, 0].set_title('Quaternion X')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('qx')
    axes[0, 0].grid(True, alpha=0.3)
    
    axes[0, 1].plot(time, quat_y, 'g-', linewidth=2)
    axes[0, 1].set_title('Quaternion Y')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('qy')
    axes[0, 1].grid(True, alpha=0.3)
    
    axes[0, 2].plot(time, quat_z, 'r-', linewidth=2)
    axes[0, 2].set_title('Quaternion Z')
    axes[0, 2].set_xlabel('Time (s)')
    axes[0, 2].set_ylabel('qz')
    axes[0, 2].grid(True, alpha=0.3)
    
    # Angular velocity plots
    axes[1, 0].plot(time, ang_vel_x, 'b-', linewidth=2)
    axes[1, 0].set_title('Angular Velocity X')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('ω_x (rad/s)')
    axes[1, 0].grid(True, alpha=0.3)
    
    axes[1, 1].plot(time, ang_vel_y, 'g-', linewidth=2)
    axes[1, 1].set_title('Angular Velocity Y')
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('ω_y (rad/s)')
    axes[1, 1].grid(True, alpha=0.3)
    
    axes[1, 2].plot(time, ang_vel_z, 'r-', linewidth=2)
    axes[1, 2].set_title('Angular Velocity Z')
    axes[1, 2].set_xlabel('Time (s)')
    axes[1, 2].set_ylabel('ω_z (rad/s)')
    axes[1, 2].grid(True, alpha=0.3)
    
    # Quaternion W and Yaw plots
    axes[2, 0].plot(time, quat_w, 'm-', linewidth=2)
    axes[2, 0].set_title('Quaternion W')
    axes[2, 0].set_xlabel('Time (s)')
    axes[2, 0].set_ylabel('qw')
    axes[2, 0].grid(True, alpha=0.3)
    
    # Unwrap yaw angle to avoid jumps at ±π
    yaw_unwrapped = np.unwrap(yaw)
    axes[2, 1].plot(time, yaw_unwrapped, 'k-', linewidth=2)
    axes[2, 1].set_title('Yaw Angle (Unwrapped)')
    axes[2, 1].set_xlabel('Time (s)')
    axes[2, 1].set_ylabel('Yaw (rad)')
    axes[2, 1].grid(True, alpha=0.3)
    
    # Quaternion magnitude check
    quat_mag = np.sqrt(quat_x**2 + quat_y**2 + quat_z**2 + quat_w**2)
    axes[2, 2].plot(time, quat_mag, 'c-', linewidth=2)
    axes[2, 2].axhline(y=1.0, color='r', linestyle='--', alpha=0.7, label='Unit magnitude')
    axes[2, 2].set_title('Quaternion Magnitude')
    axes[2, 2].set_xlabel('Time (s)')
    axes[2, 2].set_ylabel('|q|')
    axes[2, 2].grid(True, alpha=0.3)
    axes[2, 2].legend()
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'orientation_angular_velocity.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved orientation/angular velocity plot to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Plot odometry data from CSV file')
    parser.add_argument('csv_path', nargs='?', help='Path to CSV file (optional)')
    args = parser.parse_args()
    
    # Determine CSV file to use
    if args.csv_path:
        csv_path = args.csv_path
        if not os.path.exists(csv_path):
            print(f"Error: CSV file not found: {csv_path}")
            sys.exit(1)
    else:
        csv_path = find_most_recent_odom_csv()
        if csv_path is None:
            sys.exit(1)
    
    # Load data
    print(f"Loading data from: {csv_path}")
    (time, pos_x, pos_y, pos_z, quat_x, quat_y, quat_z, quat_w,
     vel_x, vel_y, vel_z, ang_vel_x, ang_vel_y, ang_vel_z, yaw) = load_odom_data(csv_path)
    
    print(f"Loaded {len(time)} data points spanning {time[-1] - time[0]:.2f} seconds")
    
    # Determine save directory (same as CSV file)
    save_dir = os.path.dirname(csv_path)
    
    # Create plots
    plot_position_velocity(time, pos_x, pos_y, pos_z, vel_x, vel_y, vel_z, save_dir)
    plot_orientation_angular_velocity(time, quat_x, quat_y, quat_z, quat_w,
                                     ang_vel_x, ang_vel_y, ang_vel_z, yaw, save_dir)
    
    print("Plotting complete!")


if __name__ == "__main__":
    main()