#!/usr/bin/env python3
"""
Script to plot control data from CSV files generated by the controller.

Usage:
    python plot_ctrl.py [--data=/path/to/folder] [--start-time=5.0] [--end-time=30.0]
    
If no data path is provided, uses the most recent folder from ctrl_logs.
"""

import argparse
import csv
import glob
import os
import sys
from pathlib import Path
from typing import Optional, Tuple, List, Dict, Any
import ast

import matplotlib.pyplot as plt
import numpy as np
import yaml


def find_most_recent_ctrl_folder() -> Optional[str]:
    """Find the most recent control log folder in ctrl_logs directory."""
    # Get ROBOT_RL_ROOT from environment
    robot_rl_root = os.environ.get("ROBOT_RL_ROOT", "")
    if not robot_rl_root:
        print("Error: ROBOT_RL_ROOT environment variable not set")
        return None
    
    ctrl_logs_dir = os.path.join(robot_rl_root, "ctrl_logs")
    if not os.path.exists(ctrl_logs_dir):
        print(f"Error: ctrl_logs directory not found at {ctrl_logs_dir}")
        return None
    
    # Find all timestamped subdirectories
    folders = glob.glob(os.path.join(ctrl_logs_dir, "*"))
    folders = [f for f in folders if os.path.isdir(f)]
    
    if not folders:
        print(f"Error: No control log folders found in {ctrl_logs_dir}")
        return None
    
    # Sort by modification time and return most recent
    folders.sort(key=os.path.getmtime, reverse=True)
    most_recent = folders[0]
    print(f"Using most recent folder: {most_recent}")
    return most_recent


def load_config(folder_path: str) -> Dict[str, Any]:
    """Load configuration from YAML file in the log folder."""
    yaml_files = glob.glob(os.path.join(folder_path, "*.yaml"))
    if not yaml_files:
        print("Warning: No YAML config file found in log folder")
        return {}
    
    config_path = yaml_files[0]  # Use the first YAML file found
    print(f"Loading config from: {config_path}")
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        return config
    except Exception as e:
        print(f"Error loading config: {e}")
        return {}


def parse_observation_data(obs_str: str) -> np.ndarray:
    """Parse observation string from CSV into numpy array."""
    try:
        # Convert string representation of list to actual list
        obs_list = ast.literal_eval(obs_str)
        return np.array(obs_list, dtype=np.float32)
    except Exception as e:
        print(f"Error parsing observation: {e}")
        return np.array([])


def convert_config_to_isaac_order(default_angles_config: List[float], default_angles_names: List[str]) -> np.ndarray:
    """Convert default angles from config order to Isaac order."""
    # Isaac joint order (from controller.py)
    isaac_joint_names = [
        "left_hip_pitch_joint",
        "right_hip_pitch_joint", 
        "waist_yaw_joint",
        "left_hip_roll_joint",
        "right_hip_roll_joint",
        "left_shoulder_pitch_joint",
        "right_shoulder_pitch_joint",
        "left_hip_yaw_joint",
        "right_hip_yaw_joint",
        "left_shoulder_roll_joint",
        "right_shoulder_roll_joint",
        "left_knee_joint",
        "right_knee_joint",
        "left_shoulder_yaw_joint",
        "right_shoulder_yaw_joint",
        "left_ankle_pitch_joint",
        "right_ankle_pitch_joint",
        "left_elbow_joint",
        "right_elbow_joint",
        "left_ankle_roll_joint",
        "right_ankle_roll_joint",
    ]
    
    # Create mapping from name to value from config
    config_name_to_value = {}
    for i, name in enumerate(default_angles_names):
        if i < len(default_angles_config):
            config_name_to_value[name] = default_angles_config[i]
    
    # Convert to Isaac order
    isaac_defaults = np.zeros(21)
    for isaac_idx, isaac_name in enumerate(isaac_joint_names):
        if isaac_name in config_name_to_value:
            isaac_defaults[isaac_idx] = config_name_to_value[isaac_name]
        else:
            print(f"Warning: No default angle found for {isaac_name}")
    
    return isaac_defaults


def decode_observations(observations: np.ndarray, config: Dict[str, Any]) -> Dict[str, np.ndarray]:
    """Decode observations based on the observation type and config."""
    if not config:
        print("Warning: No config available, using default decoding")
        return {"raw_observations": observations}
    
    # Get observation type and parameters
    control_params = config.get("onboard", {}).get("control", [{}])[0].get("params", {})
    obs_type = control_params.get("obs_type", "mlp")
    num_obs = control_params.get("num_obs", 74)
    qvel_scale = control_params.get("qvel_scale", 1.0)
    ang_vel_scale = control_params.get("ang_vel_scale", 1.0)
    cmd_scale = control_params.get("cmd_scale", [2.0, 2.0, 2.0])
    
    print(f"Decoding observations with type: {obs_type}, num_obs: {num_obs}")
    
    # Define joint names in Isaac order (from controller.py)
    joint_names = [
        "left_hip_pitch_joint",
        "right_hip_pitch_joint", 
        "waist_yaw_joint",
        "left_hip_roll_joint",
        "right_hip_roll_joint",
        "left_shoulder_pitch_joint",
        "right_shoulder_pitch_joint",
        "left_hip_yaw_joint",
        "right_hip_yaw_joint",
        "left_shoulder_roll_joint",
        "right_shoulder_roll_joint",
        "left_knee_joint",
        "right_knee_joint",
        "left_shoulder_yaw_joint",
        "right_shoulder_yaw_joint",
        "left_ankle_pitch_joint",
        "right_ankle_pitch_joint",
        "left_elbow_joint",
        "right_elbow_joint",
        "left_ankle_roll_joint",
        "right_ankle_roll_joint",
    ]
    
    decoded = {}
    num_joints = 21
    
    # Decode based on observation structure (from controller.py)
    if obs_type in ["mlp", "gl", "cnn"]:
        # Common structure: [ang_vel(3), proj_g(3), cmd_vel(3), joint_pos(21), joint_vel(21), past_action(21), phase(2)]
        decoded["angular_velocity"] = observations[:, :3] / ang_vel_scale
        decoded["projected_gravity"] = observations[:, 3:6]
        decoded["cmd_vel_x"] = observations[:, 6] / cmd_scale[0]
        decoded["cmd_vel_y"] = observations[:, 7] / cmd_scale[1] 
        decoded["cmd_vel_z"] = observations[:, 8] / cmd_scale[2]
        
        if obs_type == "mlp":
            # MLP: joint_pos, joint_vel, past_action, phase
            decoded["joint_positions"] = observations[:, 9:9+num_joints]
            decoded["joint_velocities"] = observations[:, 9+num_joints:9+2*num_joints] / qvel_scale
            decoded["past_actions"] = observations[:, 9+2*num_joints:9+3*num_joints]
            decoded["sin_phase"] = observations[:, 9+3*num_joints]
            decoded["cos_phase"] = observations[:, 9+3*num_joints+1]
        elif obs_type == "gl":
            # GL: joint_vel, joint_pos, past_action, phase  
            decoded["joint_velocities"] = observations[:, 9:9+num_joints] / qvel_scale
            decoded["joint_positions"] = observations[:, 9+num_joints:9+2*num_joints]
            decoded["past_actions"] = observations[:, 9+2*num_joints:9+3*num_joints]
            decoded["sin_phase"] = observations[:, 9+3*num_joints]
            decoded["cos_phase"] = observations[:, 9+3*num_joints+1]
    
    # Add joint names for plotting
    decoded["joint_names"] = joint_names
    
    return decoded


def load_ctrl_data(folder_path: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[str, Any]]:
    """Load control data from folder."""
    csv_path = os.path.join(folder_path, "g1_control.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"g1_control.csv not found in {folder_path}")
    
    # Load config
    config = load_config(folder_path)
    
    times = []
    observations = []
    actions = []
    
    print(f"Loading data from: {csv_path}")
    
    try:
        with open(csv_path, 'r') as f:
            reader = csv.reader(f)
            for row_idx, row in enumerate(reader):
                if len(row) >= 3:  # time, observation, action + action values
                    time_val = float(row[0])
                    obs_data = parse_observation_data(row[1])
                    
                    # Parse actions (remaining columns after time and observation)
                    action_data = np.array([float(x) for x in row[2:]], dtype=np.float32)
                    
                    if len(obs_data) > 0 and len(action_data) > 0:
                        times.append(time_val)
                        observations.append(obs_data)
                        actions.append(action_data)
                        
                if row_idx % 1000 == 0:
                    print(f"Loaded {row_idx} rows...")
                    
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        sys.exit(1)
    
    times = np.array(times)
    observations = np.array(observations)
    actions = np.array(actions)
    
    print(f"Loaded {len(times)} data points spanning {times[-1] - times[0]:.2f} seconds")
    print(f"Observation shape: {observations.shape}, Action shape: {actions.shape}")
    
    return times, observations, actions, config


def plot_joint_positions(times: np.ndarray, decoded_obs: Dict[str, np.ndarray], actions: np.ndarray,
                        config: Dict[str, Any], save_dir: str) -> None:
    """Plot joint angles and commanded actions."""
    joint_names = decoded_obs.get("joint_names", [f"joint_{i}" for i in range(21)])
    joint_positions = decoded_obs.get("joint_positions", np.zeros((len(times), 21)))
    
    # Get config parameters
    control_params = config.get("onboard", {}).get("control", [{}])[0].get("params", {})
    action_scale = control_params.get("action_scale", 0.25)
    default_angles_config = control_params.get("default_angles", [0.0] * 21)
    default_angles_names = control_params.get("default_angles_names", [])
    
    # Convert default angles from config order to Isaac order
    default_angles_isaac = convert_config_to_isaac_order(default_angles_config, default_angles_names)
    
    # Add default angles back to joint positions (they're stored as offsets from defaults)
    actual_joint_positions = joint_positions + default_angles_isaac
    
    # Convert actions to position targets (actions are already in Isaac order)
    commanded_positions = actions * action_scale + default_angles_isaac
    
    # Create subplots - more rows, fewer columns for wider plots
    fig, axes = plt.subplots(5, 6, figsize=(24, 15))
    fig.suptitle('Joint Angles and Commands', fontsize=16)
    
    # Define joint groupings (indices in Isaac order)
    left_leg_joints = [0, 3, 7, 11, 15, 19]  # hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll
    right_leg_joints = [1, 4, 8, 12, 16, 20]  # same for right
    waist_joint = [2]  # waist_yaw  
    left_arm_joints = [5, 9, 13, 17]  # left shoulder_pitch, shoulder_roll, shoulder_yaw, elbow
    right_arm_joints = [6, 10, 14, 18]  # right shoulder_pitch, shoulder_roll, shoulder_yaw, elbow
    
    all_joint_groups = [
        (left_leg_joints, "Left Leg", 0),
        (right_leg_joints, "Right Leg", 1), 
        (waist_joint, "Waist", 2),
        (left_arm_joints, "Left Arm", 3),
        (right_arm_joints, "Right Arm", 4)
    ]
    
    for joint_group, group_name, row in all_joint_groups:
        for col, joint_idx in enumerate(joint_group[:6]):  # Limit to 6 columns
            ax = axes[row, col]
            
            # Plot actual joint positions
            ax.plot(times, actual_joint_positions[:, joint_idx], linewidth=1, label='Actual Position', alpha=0.7)
            
            # Plot commanded positions  
            ax.plot(times, commanded_positions[:, joint_idx], linewidth=1, label='Commanded Position')
            
            ax.set_title(f"{joint_names[joint_idx]}", fontsize=10)
            ax.set_xlabel('Time (s)')
            ax.set_ylabel('Angle (rad)')
            ax.grid(True, alpha=0.3)
            ax.legend(fontsize=8)
            
        # Hide unused subplots in this row
        for col in range(len(joint_group), 6):
            axes[row, col].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'joint_positions.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved joint positions plot to: {output_path}")


def plot_joint_velocities(times: np.ndarray, decoded_obs: Dict[str, np.ndarray], save_dir: str) -> None:
    """Plot joint velocities."""
    joint_names = decoded_obs.get("joint_names", [f"joint_{i}" for i in range(21)])
    joint_velocities = decoded_obs.get("joint_velocities", np.zeros((len(times), 21)))
    
    # Create subplots - more rows, fewer columns for wider plots
    fig, axes = plt.subplots(5, 6, figsize=(24, 15))
    fig.suptitle('Joint Velocities', fontsize=16)
    
    # Define joint groupings (indices in Isaac order)
    left_leg_joints = [0, 3, 7, 11, 15, 19]  # hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll
    right_leg_joints = [1, 4, 8, 12, 16, 20]  # same for right
    waist_joint = [2]  # waist_yaw  
    left_arm_joints = [5, 9, 13, 17]  # left shoulder_pitch, shoulder_roll, shoulder_yaw, elbow
    right_arm_joints = [6, 10, 14, 18]  # right shoulder_pitch, shoulder_roll, shoulder_yaw, elbow
    
    all_joint_groups = [
        (left_leg_joints, "Left Leg", 0),
        (right_leg_joints, "Right Leg", 1), 
        (waist_joint, "Waist", 2),
        (left_arm_joints, "Left Arm", 3),
        (right_arm_joints, "Right Arm", 4)
    ]
    
    for joint_group, group_name, row in all_joint_groups:
        for col, joint_idx in enumerate(joint_group[:6]):  # Limit to 6 columns
            ax = axes[row, col]
            
            # Plot joint velocities
            ax.plot(times, joint_velocities[:, joint_idx], 'g-', linewidth=1)
            
            ax.set_title(f"{joint_names[joint_idx]}", fontsize=10)
            ax.set_xlabel('Time (s)')
            ax.set_ylabel('Velocity (rad/s)')
            ax.grid(True, alpha=0.3)
            
        # Hide unused subplots in this row
        for col in range(len(joint_group), 6):
            axes[row, col].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'joint_velocities.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved joint velocities plot to: {output_path}")


def plot_commands_and_phase(times: np.ndarray, decoded_obs: Dict[str, np.ndarray], 
                           save_dir: str) -> None:
    """Plot commanded velocities, angular velocity, and gait phase."""
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    fig.suptitle('Commands, IMU Data, and Gait Phase', fontsize=16)
    
    # Command velocities
    axes[0, 0].plot(times, decoded_obs.get("cmd_vel_x", np.zeros(len(times))), 'b-', linewidth=2)
    axes[0, 0].set_title('Command Velocity X')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('Velocity (m/s)')
    axes[0, 0].grid(True, alpha=0.3)
    
    axes[0, 1].plot(times, decoded_obs.get("cmd_vel_y", np.zeros(len(times))), 'g-', linewidth=2)
    axes[0, 1].set_title('Command Velocity Y')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Velocity (m/s)')
    axes[0, 1].grid(True, alpha=0.3)
    
    axes[0, 2].plot(times, decoded_obs.get("cmd_vel_z", np.zeros(len(times))), 'r-', linewidth=2)
    axes[0, 2].set_title('Command Angular Velocity Z')
    axes[0, 2].set_xlabel('Time (s)')
    axes[0, 2].set_ylabel('Angular Velocity (rad/s)')
    axes[0, 2].grid(True, alpha=0.3)
    
    # IMU data
    ang_vel = decoded_obs.get("angular_velocity", np.zeros((len(times), 3)))
    axes[1, 0].plot(times, ang_vel[:, 0], 'b-', linewidth=1, label='ω_x')
    axes[1, 0].plot(times, ang_vel[:, 1], 'g-', linewidth=1, label='ω_y') 
    axes[1, 0].plot(times, ang_vel[:, 2], 'r-', linewidth=1, label='ω_z')
    axes[1, 0].set_title('Angular Velocity (IMU)')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Angular Velocity (rad/s)')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend()
    
    # Projected gravity
    proj_g = decoded_obs.get("projected_gravity", np.zeros((len(times), 3)))
    axes[1, 1].plot(times, proj_g[:, 0], 'b-', linewidth=1, label='g_x')
    axes[1, 1].plot(times, proj_g[:, 1], 'g-', linewidth=1, label='g_y')
    axes[1, 1].plot(times, proj_g[:, 2], 'r-', linewidth=1, label='g_z')
    axes[1, 1].set_title('Projected Gravity')
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('Gravity Component')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend()
    
    # Gait phase
    if "sin_phase" in decoded_obs and "cos_phase" in decoded_obs:
        axes[1, 2].plot(times, decoded_obs["sin_phase"], 'b-', linewidth=2, label='sin(phase)')
        axes[1, 2].plot(times, decoded_obs["cos_phase"], 'r-', linewidth=2, label='cos(phase)')
        axes[1, 2].set_title('Gait Phase')
        axes[1, 2].set_xlabel('Time (s)')
        axes[1, 2].set_ylabel('Phase')
        axes[1, 2].grid(True, alpha=0.3)
        axes[1, 2].legend()
    else:
        axes[1, 2].text(0.5, 0.5, 'Phase data\nnot available', ha='center', va='center', transform=axes[1, 2].transAxes)
        axes[1, 2].set_title('Gait Phase')
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'commands_and_phase.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved commands and phase plot to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Plot control data from CSV files')
    parser.add_argument('--data', help='Path to control log folder (if not provided, uses most recent)')
    parser.add_argument('--start-time', type=float, default=0.0, help='Start time for plotting (seconds, default: 0.0)')
    parser.add_argument('--end-time', type=float, default=None, help='End time for plotting (seconds, default: None - use all data)')
    args = parser.parse_args()
    
    # Determine folder to use
    if args.data:
        folder_path = args.data
        if not os.path.exists(folder_path):
            print(f"Error: Folder not found: {folder_path}")
            sys.exit(1)
    else:
        folder_path = find_most_recent_ctrl_folder()
        if folder_path is None:
            sys.exit(1)
    
    # Load data
    times, observations, actions, config = load_ctrl_data(folder_path)
    
    # Apply time filtering
    start_time = args.start_time
    end_time = args.end_time
    
    # Find indices for time range
    start_idx = np.searchsorted(times, start_time)
    start_idx = max(0, min(start_idx, len(times) - 1))
    
    if end_time is not None:
        end_idx = np.searchsorted(times, end_time)
        end_idx = max(0, min(end_idx, len(times)))
        print(f"Plotting data from time {times[start_idx]:.2f}s to {times[min(end_idx-1, len(times)-1)]:.2f}s")
    else:
        end_idx = len(times)
        print(f"Plotting data from time {times[start_idx]:.2f}s to end at {times[-1]:.2f}s")
    
    # Slice data
    times = times[start_idx:end_idx]
    observations = observations[start_idx:end_idx]
    actions = actions[start_idx:end_idx]
    
    # Decode observations
    decoded_obs = decode_observations(observations, config)
    
    # Create plots
    plot_joint_positions(times, decoded_obs, actions, config, folder_path)
    plot_joint_velocities(times, decoded_obs, folder_path)
    plot_commands_and_phase(times, decoded_obs, folder_path)
    
    print("Plotting complete!")


if __name__ == "__main__":
    main()