# G1_21j config
robot_name: "g1_21j"
# For the mass randomization figure I used "cur_dec_1_alpha_0.5_rough_less_less_angular.pt"
# Decreasing comparison used: "hzd_dec_0.pt", "hzd_dec_1_alpha_0.5.pt", "hzd_dec_2_alpha_0.5.pt", "hzd_dec_4_alpha_1.pt"

checkpoint_path: "g1_policies/hzd/running_hzd_clf/2025-09-11_23-13-30_custom_plate_gl7/exported/policy.pt"
  # Ablation
#  "g1_policies/hzd/running_hzd_clf/2025-09-10_17-41-40_clf_ablation_gl7/exported/policy.pt"
#  "g1_policies/hzd/running_hzd_clf/2025-09-10_22-42-02_clf_ablation_w15_gl7/exported/policy.pt"
#  "g1_policies/hzd/running_hzd_clf/2025-09-08_21-13-54_torque_lim_test/exported/policy.pt"
  # Others
  #"g1_policies/hzd/running_hzd_clf/2025-09-10_09-09-59_tor_lim_1_gl5-2/exported/policy.pt" # Has the nicest looking high speed gait - does NOT work on hardware
  #"g1_policies/hzd/running_hzd_clf/2025-09-04_00-11-31_y_pd_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-09_17-19-18_tor_lim_1_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-08_22-45-09_torque_l2_2e-4_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-08_20-24-34_torque_l2_e-4_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-08_21-13-54_torque_lim_test/exported/policy.pt"   # Best on hardware - prevents most overheating
  #"g1_policies/hzd/running_hzd_clf/2025-09-07_11-58-19_partial_pd_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-07_23-21-45_fl_af_15_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-07_18-31-13_v_curr_stand_cmd_update_gl7/exported/policy.pt"   # Best on hardware so far
  #"g1_policies/hzd/running_hzd_clf/2025-09-07_11-58-19_partial_pd_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-06_09-37-28_fl_af_2_eta_035_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-06_09-36-07_fl_af_2_eta_03_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-06_23-10-23_new_weights_eta_03_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-06_10-17-41_fl_af_2_con_pen_4_eta_035_inc_y_push_inc_yaw_start_gl7/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-04_00-11-31_y_pd_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-02_22-12-29_y_cmd_no_con_pen_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-02_17-40-58_flt_aft_2_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-02_22-12-29_y_cmd_no_con_pen_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-01_15-54-58_yaw_inc_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-09-01_15-42-29_yaw_mod_gl5-2/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-08-31_18-59-53_yaw_modification_gl5/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-08-31_10-05-05/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-08-29_12-21-47/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-08-29_16-22-40/exported/policy.pt"
  #"g1_policies/hzd/running_hzd_clf/2025-08-28_15-37-29/exported/policy.pt" # OG running + standing

num_obs: 74
num_action: 21
period: 0.71                  # s
dt: 0.02                      # 50 Hz
ang_vel_scale: 1.0
command_scale: [2, 2, 2]
qpos_scale: 1
qvel_scale: 0.05 #0.1
action_scale: 0.25
height_map_scale: null        # Explicitly set to null for non-height-sensor version
def_ang_order: "mj"
default_angles: [-0.25, 0, 0, 0.46, -0.25, 0,
                  -0.25, 0, 0, 0.46, -0.25, 0,
                  0,
                  0.07, 0.24, 0, 1.39,
                  0.07, -0.24, 0, 1.39]
log: true
log_dir: "logs"
policy_type: "mlp"
use_pd: true