# G1_21j config
robot_name: "g1_21j"
checkpoint_path: "g1_policies/hzd/running_hzd_clf/2025-09-08_21-13-54_torque_lim_test/exported/policy.pt"

num_obs: 74
num_action: 21
period: 0.71                  # s
dt: 0.02                      # 50 Hz
ang_vel_scale: 1.0
command_scale: [2, 2, 2]
qpos_scale: 1
qvel_scale: 0.05 #0.1
action_scale: 0.25
height_map_scale: null        # Explicitly set to null for non-height-sensor version
def_ang_order: "mj"
default_angles: [-0.25, 0, 0, 0.46, -0.25, 0,
                  -0.25, 0, 0, 0.46, -0.25, 0,
                  0,
                  0.07, 0.24, 0, 1.39,
                  0.07, -0.24, 0, 1.39]
log: true
log_dir: "logs"
policy_type: "mlp"
use_pd: true