# G1_21j config
robot_name: "g1_21j_compute"
# For the mass randomization figure I used "cur_dec_1_alpha_0.5_rough_less_less_angular.pt"
# Decreasing comparison used: "hzd_dec_0.pt", "hzd_dec_1_alpha_0.5.pt", "hzd_dec_2_alpha_0.5.pt", "hzd_dec_4_alpha_1.pt"

checkpoint_path: "g1_policies/hzd/hzd_clf_custom/2025-10-17_17-30-28_gait_lib_no_dec/exported/policy.pt"

  #"ral_paper/hzd_dec_0.pt"
  #"g1_policies/hzd/hzd_clf_custom/2025-10-17_17-30-28_gait_lib_no_dec/exported/policy.pt"
  #"g1_policies/hzd/hzd_clf_custom/2025-10-17_14-58-28_gait_lib_dec/exported/policy.pt"
  #"ral_paper/paper_policy/8_1_alpha_2.pt"

num_obs: 74
num_action: 21
period: 0.8                  # s
dt: 0.02                      # 50 Hz
ang_vel_scale: 1.0
command_scale: [2, 2, 2]
qpos_scale: 1
qvel_scale: 0.05 #0.1
action_scale: 0.25
height_map_scale: null        # Explicitly set to null for non-height-sensor version
def_ang_order: "mj"
default_angles: [-0.25, 0, 0, 0.46, -0.25, 0,
                  -0.25, 0, 0, 0.46, -0.25, 0,
                  0,
                  0.07, 0.24, 0, 1.39,
                  0.07, -0.24, 0, 1.39]
log: true
log_dir: "logs"
policy_type: "mlp"